---
image: ligo/publisher:latest

publish:
  before_script:
    - cd final_paper
    - echo $CI_COMMIT_SHA | cut -b1-8 > gitID.txt
  script:
    - make draft
  after_script:
    - rm gitID.txt
  cache:
    key: "$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/$CI_JOB_NAME"
    untracked: true
  artifacts:
    expire_in: 4w
    paths:
      - grb_beams_paper.pdf

